### ISSUE TITLE
Are we there yet?

### ISSUE THREAD

**Issue by volodymyr-kushnir** [DimaSmolts/homepage#23]
Ну даааавай, ну релізь вже того свого Погбу, ну ж нетерпиться вже дивитись, ну. Між іншим, Моурінью не його тренер, а Юнайтед — не його команда. В Реал треба хлопцю, не червоний він. Еррера червоний, а він нє.

**Comment by volodymyr-kushnir** [comment]
А, атмєна, вже є, вже на місці. :D

**Comment by volodymyr-kushnir** [comment]
@DimaSmolts забув `stackable` на зовнішньому `grid`-і — не стакається на малих екранах. А так то зійде, все на місці.

**Comment by DimaSmolts** [comment]
Спробую виправити.

**Comment by volodymyr-kushnir** [comment]
Спробуй. Це тут https://github.com/DimaSmolts/homepage/blob/develop/index.html#L19

**Comment by DimaSmolts** [comment]
Змінив, але homepage досі відображає стару сторінку
Просто зачекати?

**Comment by DimaSmolts** [comment]
Так, вже все ок, дякую :)
